import type {DesignOptions,PositionedPair} from '../primer';
export type RecordView={accession:string;title:string;gene:string;protein:string;start:number;end:number;recommendation:string};
export type Item={id:string;input:string;status:string;settings:DesignOptions;records?:RecordView[];selected?:string;reason?:string;pairs?:PositionedPair[];total?:number;search?:import('./adaptive').SearchTrace;source?:string;fetchedAt?:number;warning?:string;error?:string};
export type Batch={id:string;created_at:number;settings:DesignOptions;items:Item[];partial?:boolean;states?:{id:string;status:string}[]};
export function mergeBatch(previous:Batch|null,incoming:Batch):Batch{
 if(!incoming.partial)return incoming;
 if(!previous||previous.id!==incoming.id)throw Error('批次进度缺少完整记录，请重新载入批次。');
 const changed=new Map(incoming.items.map(i=>[i.id,i])),states=new Map(incoming.states?.map(i=>[i.id,i.status]));
 return {...previous,...incoming,partial:false,states:undefined,items:previous.items.map(i=>changed.get(i.id)||{...i,status:states.get(i.id)||i.status})};
}
export const statusText:Record<string,string>={queued:'排队中',fetching:'检索中',designing:'设计中',awaiting:'待确认转录本',complete:'已完成',no_candidates:'无合格候选',error:'检索失败'};
export function csv(batch:Batch,all:boolean){const rows:unknown[][]=[['批次','输入目标','状态','基因','转录本版本','选择依据','序列来源','序列获取时间','模式','Tm下限','Tm上限','上游范围','下游范围','去除终止密码子','候选排名','F序列5到3','F长度','F_Tm','F_GC%','F起点','F终点','R序列5到3','R长度','R_Tm','R_GC%','R起点','R终点','产物长度','产物起点','产物终点','说明','Tm模型','单价盐mM','Mg_mM','总dNTP_mM','引物nM','结构风险级别','F发卡茎bp','R发卡茎bp','F自二聚体bp','R自二聚体bp','FR异二聚体bp','FR三端互补bp','结构提示','排序理由','目标模板校验','已获取同基因其他转录本配对','自动质量优化','实际上游搜索bp','实际下游搜索bp','优化说明']];for(const item of batch.items){const r=item.records?.find(r=>r.accession===item.selected);const pairs=all?item.pairs:item.pairs?.slice(0,1);for(const [index,p] of (pairs?.length?pairs:[undefined]).entries()){const o=item.settings;rows.push([batch.id,item.input,statusText[item.status],r?.gene,item.selected,item.reason,item.source,item.fetchedAt?new Date(item.fetchedAt).toISOString():'',o.mode,o.tmMin,o.tmMax,o.upstream,o.downstream,o.removeStop,p?index+1:'',p?.forward.sequence,p?.forward.sequence.length,p?.forward.tm.toFixed(2),p?.forward.gc.toFixed(1),p?.forward.start,p?.forward.end,p?.reverse.sequence,p?.reverse.sequence.length,p?.reverse.tm.toFixed(2),p?.reverse.gc.toFixed(1),p?.reverse.start,p?.reverse.end,p?.productLength,p?.productStart,p?.productEnd,[item.error,item.warning,...(p?.warnings||[])].filter(Boolean).join('；'),p?.quality?.model||'legacy simplified',p?.quality?.conditions.monovalent,p?.quality?.conditions.magnesium,p?.quality?.conditions.dntp,p?.quality?.conditions.dna,p?.quality?.level,p?.quality?.forward.hairpinStem,p?.quality?.reverse.hairpinStem,p?.quality?.forward.homodimer.longest,p?.quality?.reverse.homodimer.longest,p?.quality?.heterodimer.longest,p?.quality?.heterodimer.threePrime,p?.quality?.reasons.join('；'),p?.quality?.ranking.join('；'),p?.target?.status,p?.isoformProducts?.map(r=>r.accession+':'+r.length).join('；'),item.search?.status,item.search?.searchedUp,item.search?.searchedDown,item.search?.message]);}}return '\uFEFF'+rows.map(row=>row.map(value=>{let s=String(value??'');if(/^[=+@\-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(',')).join('\r\n');}
