import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
const base=process.env.PRIMER_TEST_URL||'http://localhost:3000';let cookie='';
async function request(body,id){const r=await fetch(base+'/api/batches'+(id?'?id='+id:''),{headers:{...(cookie?{cookie}:{}),...(body?{'Content-Type':'application/json',origin:base}:{})},...(body?{method:'POST',body:JSON.stringify(body)}:{})});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];const json=await r.json();assert.equal(r.status,200,JSON.stringify(json));return json;}
await request();const settings={mode:'flanking',removeStop:false,tmMin:55,tmMax:65,upstream:100,downstream:100};const id=crypto.randomUUID();let batch=await request({action:'create',id,input:'VXN\nWDFY3\nWDR18\nWDR20\nWDR37\nWDR44\nWDR55\nWDR5B\nWDR83\nABI1',settings});assert.equal(batch.items.length,10);assert.equal((await request({action:'create',id,input:'VXN',settings})).items.length,10);
const unauthorized=await fetch(base+'/api/batches?id='+id);assert.equal(unauthorized.status,404);
for(let i=0;i<10;i++){batch=await request({action:'step',id});console.log('Step',i+1,batch.items.map(x=>x.input+':'+x.status).join(' '));}
assert.ok(batch.items.every(x=>!['queued','fetching','designing'].includes(x.status)));assert.ok(batch.items.some(x=>x.status==='awaiting'));assert.ok(batch.items.some(x=>x.status==='complete'));
for(const item of batch.items.filter(x=>x.status==='awaiting')){const selected=item.selected||item.records[0].accession;await request({action:'update',id,itemId:item.id,selected,settings:item.settings});batch=await request({action:'step',id});assert.equal(batch.items.find(x=>x.id===item.id).selected,selected);}
const wdr44=batch.items.find(x=>x.input==='WDR44');if(wdr44.status==='no_candidates'){await request({action:'update',id,itemId:wdr44.id,selected:wdr44.selected,settings:{...wdr44.settings,upstream:200,downstream:200}});batch=await request({action:'step',id});}
for(const item of batch.items){assert.equal(item.status,'complete',item.input+':'+item.error);assert.ok(item.pairs.length>0&&item.pairs.length<=5);assert.equal(new Set(item.pairs.map(p=>p.forward.sequence+'|'+p.reverse.sequence)).size,item.pairs.length);const r=item.records.find(x=>x.accession===item.selected);for(const p of item.pairs){assert.ok(p.productStart<=r.start&&p.productEnd>=r.end);assert.ok(p.score<=3);for(const primer of [p.forward,p.reverse]){assert.ok(primer.sequence.length>=18&&primer.sequence.length<=25);assert.ok(primer.tm>=55&&primer.tm<=65);}}}
assert.deepEqual((await request(null,id)).items,batch.items);assert.ok((await request()).some(x=>x.id===id));
console.log('HTTP PASS: 10 targets, idempotency, ownership, transcript confirmation, independent recompute, five pairs, persistence.');mkdirSync('outputs',{recursive:true});writeFileSync('outputs/batch-http-results.json',JSON.stringify({base,checkedAt:new Date().toISOString(),items:batch.items.map(({records,...item})=>item)},null,2));

const failureId=crypto.randomUUID();await request({action:'create',id:failureId,input:'THIS_GENE_DOES_NOT_EXIST_987654321\nVXN\nWDR37',settings});await Promise.all([request({action:'step',id:failureId}),request({action:'step',id:failureId})]);let failureBatch;for(let i=0;i<3;i++)failureBatch=await request({action:'step',id:failureId});assert.equal(failureBatch.items[0].status,'error');assert.equal(failureBatch.items[1].status,'complete');assert.equal(failureBatch.items[2].status,'complete');console.log('HTTP PASS: concurrent claims and individual failure isolation.');
