import assert from 'node:assert/strict';
import {chunks,query,parseReport} from '../lib/blast/core.ts';
import {database,serviceModule} from './blast-helper.mjs';
const p={itemId:'one',input:'TEST',accession:'NM_001.1',rank:1,forward:'ACGTACGTACGTACGTACGT',reverse:'TGCATGCATGCATGCATGCA',productLength:200};const c=chunks([p])[0];assert.equal(query(c).split('>').length,3);for(const c of chunks(Array.from({length:50},(_,i)=>({...p,itemId:String(i)}))))assert.ok(c.pairs.reduce((n,p)=>n+p.forward.length+p.reverse.length,0)<=1000);
const hit=(acc,from,to,sequence,taxid=9606)=>({description:[{accession:acc,title:'test RNA',taxid}],hsps:[{query_from:1,query_to:20,align_len:20,identity:20,gaps:0,hit_from:from,hit_to:to,qseq:sequence,hseq:sequence}]});
const report=(name,sequence,hits)=>({report:{program:'blastn',search_target:{db:'refseq_rna'},results:{search:{query_title:name,query_len:sequence.length,hits}}}});
const raw={BlastOutput2:[report('p0_F',p.forward,[hit(p.accession,1,20,p.forward),hit('NM_OTHER.1',50,69,p.forward),hit('XM_MOUSE.1',1,20,p.forward,10090)]),report('p0_R',p.reverse,[hit(p.accession,200,181,p.reverse),hit('NM_OTHER.1',400,381,p.reverse),hit('XM_MOUSE.1',200,181,p.reverse,10090)])]};let result=parseReport(raw,c,1000)[0];assert.equal(result.expectedFound,true);assert.equal(result.productCount,2);assert.equal(result.products[1].length,351);assert.equal(result.fHits,2);assert.equal(parseReport(raw,c,200)[0].productCount,1);
const bad=structuredClone(raw);bad.BlastOutput2[1].report.results.search.hits[0].hsps[0].hseq=p.reverse.slice(0,-1)+'T';bad.BlastOutput2[1].report.results.search.hits[0].hsps[0].identity=19;assert.equal(parseReport(bad,c,1000)[0].expectedFound,false);assert.throws(()=>parseReport({BlastOutput2:[]},c,1000));
const {BlastService}=await serviceModule();const {db,sqlite}=database();let now=100000,calls=0;const service=new BlastService(db,async(_url,options)=>{calls++;assert.equal(options.body.get('DATABASE')||'refseq_rna','refseq_rna');return options.body.get('CMD')==='Put'?new Response('RID = MOCKRID\nRTOE = 1'):Response.json(raw);},()=>now,undefined,undefined,async()=>({found:{},incomplete:true}));await service.create('job','batch','owner',[p],1000);await service.create('job','batch','owner',[p],1000);await assert.rejects(()=>service.create('job','batch','outsider',[p],1000));assert.equal((await service.list('batch','outsider')).length,0);await Promise.all([service.step('job','owner'),service.step('job','owner')]);assert.equal(calls,1);await service.step('job','owner');assert.equal(calls,1);now+=65000;await service.step('job','owner');assert.equal(calls,2);assert.equal((await service.list('batch','owner'))[0].status,'complete');assert.equal((await service.list('batch','owner'))[0].data.chunks[0].results[0].expectedFound,true);
await service.create('job2','batch','owner',[p],1000);await service.step('job2','owner');assert.equal(calls,2);now+=11000;await service.step('job2','owner');assert.equal(calls,3);console.log('PASS BLAST: split queries, query mapping, paired orientation, 3-prime mismatches, taxon exclusion, product bounds, identity, ownership, duplicate/parallel submission, global and RID rate limits.');sqlite.close();

const {readFileSync}=await import('node:fs');const real=JSON.parse(readFileSync('tests/blast-ncbi-fixture.json','utf8'));const actualPair={...p,accession:'NM_139178.4',forward:'GAAAGCTCGGAGCAGAAGCC',reverse:'AGCTCTGACGTCACCAGGGT',productLength:903};const actual=parseReport(real,chunks([actualPair])[0],20000)[0];assert.equal(actual.expectedFound,true);assert.equal(actual.products[0].accession,'NM_139178.4');assert.equal(actual.limited,true);console.log('PASS real NCBI ALKBH3 report: version recovery, expected 903-bp product, hit-cap warning.');
