import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {inputs,choose,parseRecords,defaults} from '../lib/batch/core.ts';
import {detail,pack} from '../lib/batch/store.ts';
import {mergeBatch,csv} from '../lib/batch/view.ts';
assert.equal(inputs(Array.from({length:50},(_,i)=>'GENE'+i).join('\n')).length,50);
assert.throws(()=>inputs(Array.from({length:51},(_,i)=>'GENE'+i).join('\n')));
assert.equal(inputs('ABI1\nabi1\nALKBH3').length,2);
const seeds=JSON.parse(readFileSync('data/ncbi-seeds.json','utf8')),records=parseRecords(seeds.ALKBH3.xml);
assert.equal(choose([{...records[0],recommendation:'NCBI 注释标记 MANE Select'},{...records[0],accession:'NM_000000.1',recommendation:''}],'ALKBH3').confirmed,true);
const sql=new DatabaseSync(':memory:');for(const name of readdirSync('drizzle').filter(n=>n.endsWith('.sql')))sql.exec(readFileSync('drizzle/'+name,'utf8'));
let payloadReads=0;const adapter={prepare(query){let args=[];return{bind(...a){args=a;return this},async first(){if(query.startsWith('SELECT payload'))payloadReads++;return sql.prepare(query).get(...args)||null},async all(){return{results:sql.prepare(query).all(...args)}}}}};
sql.prepare('INSERT INTO primer_batches VALUES(?,?,?,?)').run('load','owner',1,JSON.stringify(defaults));
const payload=Buffer.from(await pack({records,selected:records[0].accession}));
for(let i=0;i<50;i++)sql.prepare('INSERT INTO primer_items(id,batch_id,position,input,status,settings,payload) VALUES(?,?,?,?,?,?,?)').run('item'+i,'load',i,'GENE'+i,'queued',JSON.stringify(defaults),payload);
const full=await detail(adapter,'load','owner');assert.equal(full.items.length,50);assert.equal(payloadReads,50);assert.ok(full.items.every(i=>i.records.every(r=>!('sequence' in r))));
sql.prepare("UPDATE primer_items SET status='complete' WHERE id='item0'").run();payloadReads=0;const delta=await detail(adapter,'load','owner',['item0']);assert.equal(payloadReads,1);assert.equal(delta.items.length,1);assert.equal(delta.states.length,50);
const merged=mergeBatch(full,delta);assert.equal(merged.items.length,50);assert.equal(merged.items[0].status,'complete');assert.equal(merged.items[49].selected,full.items[49].selected);assert.equal(csv(merged,false).split('\r\n').length,51);assert.equal(await detail(adapter,'load','outsider',[]),null);
assert.throws(()=>mergeBatch(null,delta));assert.throws(()=>mergeBatch({...full,id:'other'},delta));
payloadReads=0;assert.equal((await detail(adapter,'load','owner',[])).items.length,0);assert.equal(payloadReads,0);
console.log('PASS 50-target limits, unique input, annotated transcript selection, serial hydration, compact one-item reads, 50-item merge, resume/export completeness and owner isolation.');
