export type Chemistry={monovalent:number;magnesium:number;dntp:number;dna:number};
export const defaultChemistry:Chemistry={monovalent:50,magnesium:1.5,dntp:0.6,dna:50};
export const model='SantaLucia98 + SantaLucia salt / Mg-equivalent v1';
export function chemistry(raw:unknown):Chemistry{const o=(raw??defaultChemistry) as Chemistry;if(!o||!Object.values(o).every(Number.isFinite)||!Number.isFinite(o.monovalent)||o.monovalent<1||o.monovalent>500||!Number.isFinite(o.magnesium)||o.magnesium<0||o.magnesium>20||!Number.isFinite(o.dntp)||o.dntp<0||o.dntp>10||!Number.isFinite(o.dna)||o.dna<1||o.dna>5000)throw Error('反应条件无效：单价盐 1–500 mM，Mg²⁺ 0–20 mM，总 dNTP 0–10 mM，引物有效浓度 1–5000 nM。');return {monovalent:o.monovalent,magnesium:o.magnesium,dntp:o.dntp,dna:o.dna};}
const nn:Record<string,[number,number]>={AA:[-7.9,-22.2],TT:[-7.9,-22.2],AC:[-8.4,-22.4],GT:[-8.4,-22.4],AG:[-7.8,-21],CT:[-7.8,-21],AT:[-7.2,-20.4],TA:[-7.2,-21.3],CA:[-8.5,-22.7],TG:[-8.5,-22.7],CC:[-8,-19.9],GG:[-8,-19.9],CG:[-10.6,-27.2],GA:[-8.2,-22.2],TC:[-8.2,-22.2],GC:[-9.8,-24.4]};
const complement:Record<string,string>={A:'T',T:'A',C:'G',G:'C'};
const rc=(s:string)=>[...s].reverse().map(c=>complement[c]).join('');
// SantaLucia 1998 nearest-neighbor parameters and terminal/symmetry corrections.
// Mg equivalent follows the von Ahsen approximation; concentrations enter in M.
export function nearestNeighborTm(sequence:string,conditions:Chemistry):number{if(!/^[ACGT]{2,60}$/.test(sequence))throw Error('热力学计算只接受明确的 DNA 序列。');const o=chemistry(conditions);let h=0,s=0;for(let i=0;i<sequence.length-1;i++){const v=nn[sequence.slice(i,i+2)];h+=v[0];s+=v[1];}for(const base of [sequence[0],sequence.at(-1)!]){if(base==='A'||base==='T'){h+=2.3;s+=4.1;}else{h+=0.1;s-=2.8;}}const symmetric=sequence===rc(sequence);if(symmetric)s-=1.4;const salt=(o.monovalent+120*Math.sqrt(Math.max(0,o.magnesium-o.dntp)))/1000;s+=0.368*(sequence.length-1)*Math.log(salt);return 1000*h/(s+1.987*Math.log(o.dna*1e-9/(symmetric?1:4)))-273.15;}
export type ComplementRisk={longest:number;threePrime:number};
export type OligoRisk={hairpinStem:number;hairpinLoop:number;homodimer:ComplementRisk;endGc:number;endRun:number};
// Exact contiguous Watson-Crick stems only. This is a transparent risk screen,
// not a full thermodynamic folding algorithm (no bulges or internal mismatches).
export function dimerRisk(a:string,b:string):ComplementRisk{const reversed=[...b].reverse().join('');let longest=0,threePrime=0;for(let offset=1-b.length;offset<a.length;offset++){let run=0;for(let i=Math.max(0,offset);i<Math.min(a.length,offset+b.length);i++){const j=i-offset;if(complement[a[i]]===reversed[j]){run++;longest=Math.max(longest,run);if(i===a.length-1||j-run+1===0)threePrime=Math.max(threePrime,run);}else run=0;}}return {longest,threePrime};}
export function oligoRisk(s:string):OligoRisk{let hairpinStem=0,hairpinLoop=0;for(let left=0;left<s.length;left++)for(let right=left+4;right<s.length;right++){let stem=0;while(right-left-2*stem-1>=3&&complement[s[left+stem]]===s[right-stem]){stem++;if(stem>hairpinStem){hairpinStem=stem;hairpinLoop=right-left-2*stem+1;}}}const terminal=s.at(-1);let endRun=0;for(let i=s.length-1;i>=0&&s[i]===terminal;i--)endRun++;return {hairpinStem,hairpinLoop,homodimer:dimerRisk(s,s),endGc:[...s.slice(-5)].filter(x=>x==='G'||x==='C').length,endRun};}
export type Quality={model:string;conditions:Chemistry;forward:OligoRisk;reverse:OligoRisk;heterodimer:ComplementRisk;riskCount:number;level:'low'|'review'|'high';reasons:string[];ranking:string[]};
export function pairQuality(f:string,r:string,conditions:Chemistry,fr=oligoRisk(f),rr=oligoRisk(r)):Quality{const heterodimer=dimerRisk(f,r),reasons:string[]=[];let high=false;for(const [name,o] of [['F',fr],['R',rr]] as const){if(o.hairpinStem>=4)reasons.push(`${name} 潜在发卡：连续茎 ${o.hairpinStem} bp，环 ${o.hairpinLoop} nt`);if(o.homodimer.longest>=6)reasons.push(`${name} 自二聚体连续互补 ${o.homodimer.longest} bp`);if(o.homodimer.threePrime>=4){reasons.push(`${name} 自二聚体涉及 3′端的连续互补 ${o.homodimer.threePrime} bp`);high=true;}if(o.endGc>=4)reasons.push(`${name} 3′端最后 5 nt 中 GC 为 ${o.endGc}`);if(o.endRun>=3)reasons.push(`${name} 3′端连续相同碱基 ${o.endRun} nt`);}if(heterodimer.longest>=6)reasons.push(`F/R 异二聚体连续互补 ${heterodimer.longest} bp`);if(heterodimer.threePrime>=4){reasons.push(`F/R 异二聚体涉及 3′端的连续互补 ${heterodimer.threePrime} bp`);high=true;}return {model,conditions,forward:fr,reverse:rr,heterodimer,riskCount:reasons.length,level:high?'high':reasons.length?'review':'low',reasons,ranking:[]};}
