import {ncbiBindings} from '@/db/bindings';
import {D1Store} from '@/lib/ncbi/store';
import {createService} from '@/lib/ncbi/service';
import seeds from '@/data/ncbi-seeds.json';
import {inputs,settings,parseRecords,choose,five,screenIsoforms,type ItemData} from '@/lib/batch/core';
import {session,sameOrigin,detail,pack,unpack,type Row} from '@/lib/batch/store';
import {adaptiveDesign,qualityIssues} from '@/lib/batch/adaptive';
export async function GET(request:Request){const s=await session(request);try{const {db}=ncbiBindings();const url=new URL(request.url);const id=url.searchParams.get('id');if(id){const result=await detail(db,id,s.owner);return Response.json(result||{error:'批次不存在，或不属于当前会话。'},{status:result?200:404,headers:s.headers});}const before=Number(url.searchParams.get('before')||Date.now()+1);const rows=await db.prepare('SELECT b.id,b.created_at,(SELECT COUNT(*) FROM primer_items i WHERE i.batch_id=b.id) AS count FROM primer_batches b WHERE owner=? AND created_at<? ORDER BY created_at DESC LIMIT 20').bind(s.owner,before).all();return Response.json(rows.results,{headers:s.headers});}catch{return Response.json({error:'无法读取批次，请稍后重试。'},{status:503,headers:s.headers});}}
export async function POST(request:Request){const s=await session(request);try{sameOrigin(request);if(Number(request.headers.get('content-length')||0)>20000)throw Error('请求过大。');const body=await request.json() as {action:string;id:string;input?:string;settings?:unknown;itemId?:string;selected?:string;compact?:boolean};const {db,apiKey,email}=ncbiBindings();
 if(body.action==='create'){const list=inputs(body.input),o=settings(body.settings);if(!/^[0-9a-f-]{36}$/.test(body.id||''))throw Error('批次编号无效。');const existing=await db.prepare('SELECT owner FROM primer_batches WHERE id=?').bind(body.id).first<{owner:string}>();if(existing&&existing.owner!==s.owner)throw Error('批次编号不可用。');if(!existing)await db.batch([db.prepare('INSERT INTO primer_batches(id,owner,created_at,settings) VALUES(?,?,?,?)').bind(body.id,s.owner,Date.now(),JSON.stringify(o)),...list.map((input,position)=>db.prepare('INSERT INTO primer_items(id,batch_id,position,input,status,settings) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),body.id,position,input,'queued',JSON.stringify(o)))]);return Response.json(await detail(db,body.id,s.owner),{headers:s.headers});}
 const batch=await db.prepare('SELECT id FROM primer_batches WHERE id=? AND owner=?').bind(body.id||'',s.owner).first();if(!batch)return Response.json({error:'批次不存在，或不属于当前会话。'},{status:404,headers:s.headers});
 if(body.action==='update'){const row=await db.prepare('SELECT * FROM primer_items WHERE id=? AND batch_id=?').bind(body.itemId||'',body.id).first<Row>();if(!row)throw Error('未找到目标。');if(['fetching','designing'].includes(row.status)&&row.lease_until>Date.now())return Response.json({error:'目标正在处理，请稍后修改。'},{status:409,headers:s.headers});const data=await unpack(row.payload);const o=settings(body.settings||JSON.parse(row.settings));if(body.selected){if(!data.records?.some(r=>r.accession===body.selected))throw Error('请选择此目标已检索到的转录本。');data.selected=body.selected;data.reason='用户确认的目标转录本';}if(row.status==='awaiting'&&!body.selected)throw Error('请先确认转录本。');delete data.error;delete data.pairs;delete data.total;delete data.search;const updated=await db.prepare("UPDATE primer_items SET status='queued',settings=?,payload=?,lease=NULL,lease_until=0 WHERE id=? AND (lease_until<=? OR status NOT IN ('fetching','designing')) RETURNING id").bind(JSON.stringify(o),await pack(data),row.id,Date.now()).first();if(!updated)return Response.json({error:'目标正在处理，请稍后修改。'},{status:409,headers:s.headers});return Response.json(await detail(db,body.id,s.owner),{headers:s.headers});}
 if(body.action==='optimize_quality'){
 const rows=await db.prepare("SELECT id,settings FROM primer_items WHERE batch_id=? AND status='complete'").bind(body.id).all<{id:string;settings:string}>();
 for(const r of rows.results){const o=settings(JSON.parse(r.settings));if(o.mode!=='flanking')continue;const saved=await db.prepare('SELECT payload FROM primer_items WHERE id=? AND batch_id=?').bind(r.id,body.id).first<{payload:ArrayBuffer}>();const data=await unpack(saved?.payload||null);if(!data.pairs?.some(p=>qualityIssues(p).length))continue;delete data.pairs;delete data.search;delete data.total;delete data.error;await db.prepare("UPDATE primer_items SET status='queued',settings=?,payload=?,lease=NULL,lease_until=0 WHERE id=? AND batch_id=? AND status='complete'").bind(JSON.stringify({...o,autoExpandRepeats:true}),await pack(data),r.id,body.id).run();}
 return Response.json(await detail(db,body.id,s.owner),{headers:s.headers});
 }
 if(body.action==='retry_errors'){await db.prepare("UPDATE primer_items SET status='queued',lease=NULL,lease_until=0 WHERE batch_id=? AND status='error'").bind(body.id).run();return Response.json(await detail(db,body.id,s.owner),{headers:s.headers});}
 if(body.action!=='step')throw Error('未知操作。');const now=Date.now(),lease=crypto.randomUUID();
 // Claim one item across tabs; expired work can be resumed after a browser disconnect.
 const row=await db.prepare("UPDATE primer_items SET status='fetching',lease=?,lease_until=? WHERE id=(SELECT id FROM primer_items WHERE batch_id=? AND (status='queued' OR (status IN ('fetching','designing') AND lease_until<=?)) ORDER BY position LIMIT 1) AND NOT EXISTS(SELECT 1 FROM primer_items WHERE batch_id=? AND status IN ('fetching','designing') AND lease_until>?) RETURNING *").bind(lease,now+120000,body.id,now,body.id,now).first<Row>();
 if(row){let data:ItemData=await unpack(row.payload);let status='complete';try{if(!data.records?.length){const response=await createService({store:new D1Store(db),apiKey,email,seeds}).search(row.input);const records=parseRecords(response.xml);if(!records.length)throw Error('没有可用的完整人类 NM 转录本，请核对名称或输入 NM 编号。');const choice=choose(records,row.input);data={records,selected:choice.selected,reason:choice.reason,source:response.source,fetchedAt:response.fetchedAt,warning:response.warning};if(!choice.confirmed)status='awaiting';}
 if(status!=='awaiting'){const selected=data.records?.find(r=>r.accession===data.selected);if(!selected)throw Error('请确认目标转录本。');await db.prepare("UPDATE primer_items SET status='designing' WHERE id=? AND lease=?").bind(row.id,lease).run();const o=settings(JSON.parse(row.settings));try{const result=adaptiveDesign(selected,data.records||[],o);data.pairs=result.pairs;data.total=result.total;data.search=result.search;if(!data.pairs.length){status='no_candidates';data.error=result.search.message;}else delete data.error;}catch(e){status='no_candidates';data.pairs=[];delete data.search;data.error=e instanceof Error?e.message:'当前条件无法设计。';}}}
 catch(e){status='error';data.error=e instanceof Error?e.message:'处理失败，请重试。';}
 await db.prepare('UPDATE primer_items SET status=?,payload=?,lease=NULL,lease_until=0 WHERE id=? AND lease=?').bind(status,await pack(data),row.id,lease).run();}
 return Response.json(await detail(db,body.id,s.owner,body.compact?(row?[row.id]:[]):undefined),{headers:s.headers});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'批次服务暂时不可用。'},{status:400,headers:s.headers});}}
