import {evaluateReport,type PairDetails,type Evaluation} from './pair-engine';
import type {ClassifiedProduct,VerificationSummary} from './classification';
import type {TargetCheck} from './target';
export type Selection={itemId:string;rank:number;input:string;accession:string;forward:string;reverse:string;productLength:number;fullForward?:string;fullReverse?:string;target?:TargetCheck};
export type Match={accession:string;title:string;from:number;to:number;mismatches:number;identity:number;threePrime:boolean};
export type Product=Partial<ClassifiedProduct> & {accession:string;title:string;start:number;end:number;length:number;expected:boolean;fMismatches:number;rMismatches:number;pair?:PairDetails;predicted?:boolean;geneRelation?:'same_gene'|'other_gene'|'unknown'};
export type SearchEvidence={scope:'human_confirmed'|'unconfirmed'|'legacy';hitLimit:number;fReturned:number;rReturned:number;fHuman:number;rHuman:number;truncated:boolean;speciesMissing:boolean;databaseSequences?:number};
export type CheckResult={key:string;input:string;rank:number;accession:string;forward:string;reverse:string;fHits:number;rHits:number;expectedFound:boolean;products:Product[];productCount:number;limited:boolean;evaluation?:Evaluation;target?:TargetCheck;evidence?:SearchEvidence;annotationIncomplete?:boolean;summary?:VerificationSummary;notes:string[]};
export type Chunk={pairs:Selection[];engineVersion?:'2.0';database?:'refseq_rna'|'refseq_genomic';scope?:'human';hitLimit?:number;rid?:string;status:'queued'|'submitting'|'waiting'|'complete'|'error';nextAt:number;results?:CheckResult[];error?:string;failures?:number;completedAt?:number};
export type JobData={chunks:Chunk[];maxProduct:number;database:string};
export type Job={id:string;batchId:string;createdAt:number;status:string;nextAt:number;data:JobData};
export const signature=(s:Selection)=>s.itemId+'|'+s.accession+'|'+s.forward+'|'+s.reverse;
export function chunks(pairs:Selection[],maxBases=1000):Chunk[]{const output:Chunk[]=[];let current:Selection[]=[],length=0;for(const pair of pairs){const n=pair.forward.length+pair.reverse.length;if(length+n>maxBases){output.push({pairs:current,status:'queued',nextAt:0});current=[];length=0;}current.push(pair);length+=n;}if(current.length)output.push({pairs:current,status:'queued',nextAt:0});return output;}
export function query(chunk:Chunk){return chunk.pairs.map((p,i)=>`>p${i}_F\n${p.forward}\n>p${i}_R\n${p.reverse}`).join('\n');}
export function primerBlastUrl(p:Selection){const params=new URLSearchParams({INPUT_SEQUENCE:p.accession,PRIMER_LEFT_INPUT:p.forward,PRIMER_RIGHT_INPUT:p.reverse,ORGANISM:'Homo sapiens (taxid:9606)'});return 'https://www.ncbi.nlm.nih.gov/tools/primer-blast/?'+params;}
export function parseReport(raw:unknown,chunk:Chunk,maxProduct:number):CheckResult[]{
 if(chunk.engineVersion==='2.0')return evaluateReport(raw,chunk,maxProduct);
 const root=raw as any;const reports=root?.BlastOutput2;if(!Array.isArray(reports)||reports.length!==chunk.pairs.length*2)throw Error('BLAST 返回的查询数量不完整，无法生成验证结论。');
 const mapped=new Map<string,{matches:Match[];limited:boolean;unknown:boolean;returned:number;human:number;scope:boolean;databaseSequences?:number}>();
 for(const entry of reports){const report=entry.report,search=report?.results?.search;if(!search||report.program!=='blastn'||report.search_target?.db!=='refseq_rna')throw Error('BLAST 返回的程序或数据库与提交设置不符。');const name=String(search.query_title||'').split(/\s/)[0];if(!/^p\d+_[FR]$/.test(name)||mapped.has(name))throw Error('BLAST 查询标识无法对应到引物。');const index=Number(name.slice(1,-2)),pair=chunk.pairs[index];if(!pair)throw Error('未知引物查询。');const sequence=name.endsWith('_F')?pair.forward:pair.reverse;if(search.query_len!==sequence.length)throw Error('BLAST 查询长度不一致。');const hits=search.hits||[];const matches:Match[]=[];let unknown=false;let humanCount=0,nonHuman=false;for(const hit of hits){const descriptions=hit.description||[];const human=descriptions.filter((d:any)=>Number(d.taxid)===9606||d.sciname==='Homo sapiens');if(human.length)humanCount++;if(descriptions.some((d:any)=>d.taxid&&Number(d.taxid)!==9606||d.sciname&&d.sciname!=='Homo sapiens'))nonHuman=true;if(!descriptions.length||descriptions.some((d:any)=>!d.taxid&&!d.sciname))unknown=true;for(const hsp of hit.hsps||[]){if(hsp.query_from!==1||hsp.query_to!==sequence.length||hsp.align_len!==sequence.length||(hsp.gaps||0)!==0)continue;const mismatch=sequence.length-hsp.identity;if(mismatch>2)continue;const q=String(hsp.qseq||'').toUpperCase(),h=String(hsp.hseq||'').toUpperCase();if(q!==sequence||h.length!==sequence.length)continue;const threePrime=q.slice(-5)===h.slice(-5);if(!threePrime)continue;for(const d of human){matches.push({accession:String(d.id||'').match(/(?:ref|gb|emb|dbj)\|([^|]+)\|/)?.[1]||d.accession,title:d.title||'',from:hsp.hit_from,to:hsp.hit_to,mismatches:mismatch,identity:hsp.identity,threePrime});}}}mapped.set(name,{matches,limited:hits.length>=(chunk.hitLimit||100),unknown,returned:hits.length,human:humanCount,scope:report.params?.entrez_query==='txid9606[ORGN]'&&!nonHuman&&!unknown,databaseSequences:search.stat?.db_num});}
 return chunk.pairs.map((pair,index)=>{const f=mapped.get(`p${index}_F`),r=mapped.get(`p${index}_R`);if(!f||!r)throw Error('缺少 F 或 R 的查询结果。');const products=new Map<string,Product>();for(const a of f.matches)for(const b of r.matches){if(a.accession!==b.accession||(a.from<a.to)===(b.from<b.to))continue;const plus=a.from<a.to?a:b,minus=a.from>a.to?a:b;if(plus.to>=minus.to)continue;const start=plus.from,end=minus.from,length=end-start+1;if(length>maxProduct)continue;const expected=a.accession===pair.accession&&length===pair.productLength&&a.from<a.to&&a.mismatches===0&&b.mismatches===0;const p={accession:a.accession,title:a.title,start,end,length,expected,fMismatches:a.mismatches,rMismatches:b.mismatches};const key=p.accession+':'+start+':'+end;const old=products.get(key);if(!old||a.mismatches+b.mismatches<old.fMismatches+old.rMismatches)products.set(key,p);}const list=[...products.values()].sort((a,b)=>Number(b.expected)-Number(a.expected)||a.fMismatches+a.rMismatches-b.fMismatches-b.rMismatches);const scope=chunk.scope==='human'?(f.scope&&r.scope?'human_confirmed':'unconfirmed'):'legacy';const limited=f.limited||r.limited||f.unknown||r.unknown||scope!=='human_confirmed';const evidence:SearchEvidence={scope,hitLimit:chunk.hitLimit||100,fReturned:f.returned,rReturned:r.returned,fHuman:f.human,rHuman:r.human,truncated:f.limited||r.limited,speciesMissing:f.unknown||r.unknown,databaseSequences:f.databaseSequences};const notes=['仅汇总返回记录中的人源 RefSeq RNA 命中；不覆盖基因组。','配对规则：全长无缺口、每条≤2处错配、3′末端5个碱基全匹配、相向且不重叠。'];if(f.limited||r.limited)notes.push('至少一条引物达到 '+evidence.hitLimit+' 条返回记录上限，脱靶结果可能遗漏。');if(scope!=='human_confirmed')notes.push(scope==='legacy'?'旧版全物种检索后筛人源记录，请重新验证。':'无法核实人源限定已生效，不能据此排除脱靶。');if(f.unknown||r.unknown)notes.push('部分命中缺少物种注释，未计入人源结果。');if(list.length>100)notes.push('配对扩增结果仅展示前 100 条。');return {key:signature(pair),input:pair.input,rank:pair.rank,accession:pair.accession,forward:pair.forward,reverse:pair.reverse,fHits:f.matches.length,rHits:r.matches.length,expectedFound:list.some(p=>p.expected),products:list.slice(0,100),productCount:list.length,limited,target:pair.target,evidence,notes};});
}
