import {geneAnnotations} from './annotation';
import {classify} from './classification';
import {chunks,query,parseReport,type Selection,type JobData,type Job} from './core';
const endpoint='https://blast.ncbi.nlm.nih.gov/Blast.cgi';
async function encode(data:JobData){const bytes=await new Response(new Blob([JSON.stringify(data)]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer();if(bytes.byteLength>1500000)throw Error('验证结果过大，请减少勾选数量。');return bytes;}
async function decode(data:ArrayBuffer):Promise<JobData>{return JSON.parse(await new Response(new Blob([new Uint8Array(data)]).stream().pipeThrough(new DecompressionStream('gzip'))).text());}
type Row={id:string;batch_id:string;owner:string;created_at:number;status:string;next_at:number;lease:string;lease_until:number;payload:ArrayBuffer};
export class BlastService{
 constructor(private db:D1Database,private fetcher:typeof fetch=fetch,private now=Date.now,private email?:string,private apiKey?:string,private annotateGenes=geneAnnotations){}
 async list(batchId:string,owner:string):Promise<Job[]>{const rows=await this.db.prepare('SELECT * FROM blast_jobs WHERE batch_id=? AND owner=? ORDER BY created_at DESC LIMIT 10').bind(batchId,owner).all<Row>();return Promise.all(rows.results.map(async r=>({id:r.id,batchId:r.batch_id,createdAt:r.created_at,status:r.status,nextAt:r.next_at,data:await decode(r.payload)})));}
 async create(id:string,batchId:string,owner:string,pairs:Selection[],maxProduct:number,database:'refseq_rna'|'refseq_genomic'='refseq_rna'){if(!['refseq_rna','refseq_genomic'].includes(database))throw Error('验证数据库无效。');const existing=await this.db.prepare('SELECT owner FROM blast_jobs WHERE id=?').bind(id).first<{owner:string}>();if(existing){if(existing.owner!==owner)throw Error('验证编号不可用。');return;}if(!pairs.length||pairs.length>50||!Number.isInteger(maxProduct)||maxProduct<60||maxProduct>50000||pairs.some(p=>p.productLength>maxProduct))throw Error('请选择 1–50 组引物；最大扩增长度需覆盖目标产物，范围为 60–50000 bp。');await this.db.prepare('INSERT INTO blast_jobs(id,batch_id,owner,created_at,status,next_at,payload) VALUES(?,?,?,?,?,?,?)').bind(id,batchId,owner,this.now(),'queued',0,await encode({chunks:chunks(pairs,400).map(c=>({...c,scope:'human' as const,hitLimit:500,engineVersion:'2.0' as const,database})),maxProduct,database})).run();}
 async annotate(id:string,owner:string){const lease=crypto.randomUUID();const row=await this.db.prepare('UPDATE blast_jobs SET lease=?,lease_until=? WHERE id=? AND owner=? AND lease_until<=? RETURNING *').bind(lease,this.now()+60000,id,owner,this.now()).first<Row>();if(!row)throw Error('任务正在处理，请稍后补全注释。');try{const data=await decode(row.payload);const all=data.chunks.flatMap(c=>c.results||[]);const annotation=await this.annotateGenes(this.db,all.flatMap(r=>[r.accession,...r.products.map(p=>p.accession)]),this.apiKey,this.email);for(const c of data.chunks)if(c.results)c.results=c.results.map(r=>classify({...r,annotationIncomplete:!annotation.found[r.accession]||(r.evaluation?.database!=='refseq_genomic'&&r.products.some(p=>!annotation.found[p.accession]))},annotation.found));await this.db.prepare('UPDATE blast_jobs SET payload=? WHERE id=? AND lease=?').bind(await encode(data),id,lease).run();}finally{await this.db.prepare('UPDATE blast_jobs SET lease=NULL,lease_until=0 WHERE id=? AND lease=?').bind(id,lease).run();}}
 async retry(id:string,owner:string){const row=await this.db.prepare('SELECT * FROM blast_jobs WHERE id=? AND owner=?').bind(id,owner).first<Row>();if(!row)throw Error('验证记录不存在。');if(row.lease_until>this.now())throw Error('验证正在处理，请稍后重试。');const data=await decode(row.payload);for(const c of data.chunks)if(c.status==='error'){c.status=c.rid?'waiting':'queued';c.nextAt=Math.max(c.nextAt,this.now());c.failures=0;delete c.error;}await this.db.prepare("UPDATE blast_jobs SET status='queued',payload=?,lease=NULL,lease_until=0 WHERE id=? AND lease_until<=?").bind(await encode(data),id,this.now()).run();}
 async step(id:string,owner:string){const now=this.now(),lease=crypto.randomUUID();const row=await this.db.prepare('UPDATE blast_jobs SET lease=?,lease_until=? WHERE id=? AND owner=? AND lease_until<=? RETURNING *').bind(lease,now+90000,id,owner,now).first<Row>();if(!row)return;const data=await decode(row.payload);let next=now+60000;
 try{for(const c of data.chunks)if(c.status==='submitting'){c.status='error';c.error='上次提交中断，是否被 NCBI 接收未知。请手动重试，避免自动重复提交。';}const chunk=data.chunks.find(c=>(c.status==='queued'||c.status==='waiting')&&c.nextAt<=now);if(!chunk)return;
 const allowed=await this.db.prepare("INSERT INTO upstream_gate(id,next_at) VALUES('blast',?) ON CONFLICT(id) DO UPDATE SET next_at=excluded.next_at WHERE upstream_gate.next_at<=? RETURNING next_at").bind(now+11000,now).first();if(!allowed){const gate=await this.db.prepare("SELECT next_at FROM upstream_gate WHERE id='blast'").first<{next_at:number}>();next=gate?.next_at||now+11000;return;}
 let params:URLSearchParams;if(chunk.status==='queued'){chunk.status='submitting';await this.db.prepare('UPDATE blast_jobs SET payload=? WHERE id=? AND lease=?').bind(await encode(data),id,lease).run();params=new URLSearchParams({CMD:'Put',PROGRAM:'blastn',DATABASE:chunk.database||'refseq_rna',QUERY:query(chunk),WORD_SIZE:'7',EXPECT:'1000',FILTER:'F',NUCL_REWARD:'1',NUCL_PENALTY:'-3',GAPCOSTS:'5 2',HITLIST_SIZE:String(chunk.hitLimit||100),...(chunk.scope==='human'?{ENTREZ_QUERY:'txid9606[ORGN]'}:{}),SHORT_QUERY_ADJUST:'true',tool:'human_cds_primer_batch_lab'});}else params=new URLSearchParams({CMD:'Get',RID:chunk.rid!,FORMAT_TYPE:'JSON2_S',tool:'human_cds_primer_batch_lab'});if(this.email)params.set('email',this.email);chunk.nextAt=now+65000;
 try{const response=await this.fetcher(endpoint,{method:'POST',body:params,signal:AbortSignal.timeout(40000)});if(!response.ok)throw Error('NCBI 暂时无法处理验证请求（'+response.status+'）。');const text=await response.text();if(text.length>20000000)throw Error('BLAST 返回结果过大，请使用 NCBI 原始结果复核。');if(chunk.status==='submitting'){const rid=text.match(/RID\s*=\s*([A-Z0-9-]+)/)?.[1];if(!rid)throw Error('NCBI 未返回验证编号；提交状态未知，请稍后手动重试。');chunk.rid=rid;chunk.status='waiting';const eta=Number(text.match(/RTOE\s*=\s*(\d+)/)?.[1]||60);chunk.nextAt=now+Math.max(65000,eta*1000);}else if(/Status\s*=\s*WAITING/.test(text)){chunk.status='waiting';}else if(/Status\s*=\s*(FAILED|UNKNOWN)/.test(text)){chunk.status='error';chunk.error='NCBI 验证任务失败或已过期，请重新提交所选引物。';}else{let json;try{json=JSON.parse(text);}catch{throw Error('NCBI 尚未返回可解析结果，将稍后重试。');}chunk.results=parseReport(json,chunk,data.maxProduct);try{const accessions=chunk.results.flatMap(r=>[r.accession,...r.products.map(p=>p.accession)]);const annotation=await this.annotateGenes(this.db,accessions,this.apiKey,this.email);chunk.results=chunk.results.map(r=>classify({...r,annotationIncomplete:!annotation.found[r.accession]||(r.evaluation?.database!=='refseq_genomic'&&r.products.some(p=>!annotation.found[p.accession]))},annotation.found));}catch{chunk.results=chunk.results.map(r=>classify({...r,annotationIncomplete:true},{}));}chunk.status='complete';chunk.completedAt=this.now();delete chunk.error;}}
 catch(e){const message=e instanceof Error?e.message:'验证请求失败。';chunk.failures=(chunk.failures||0)+1;if(chunk.status==='submitting'||chunk.failures>=5){chunk.status='error';chunk.error=message;}else{chunk.status='waiting';chunk.error=message;}}
 }finally{const pending=data.chunks.filter(c=>['queued','waiting'].includes(c.status));next=pending.length?Math.max(next===now+60000?0:next,Math.min(...pending.map(c=>c.nextAt))):0;const status=pending.length?'waiting':data.chunks.some(c=>c.status==='error')?'error':'complete';await this.db.prepare('UPDATE blast_jobs SET status=?,next_at=?,payload=?,lease=NULL,lease_until=0 WHERE id=? AND lease=?').bind(status,next,await encode(data),id,lease).run();}}
}
